import = ["~/.config/alacritty/colors/macchiato.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
dynamic_padding = true
decorations = "Full"
# opacity= 0.7

[window.class]
general = "Alacritty"
instance = "Alacritty"
