palette = "catppuccin_macchiato"

format = """
$directory \
$character\
"""

right_format = """
$battery  \
$git_branch \
"""

[character]
success_symbol = "[îˆ¯ ](maroon)"
error_symbol = "[îˆ¯ ](red)"
vimcmd_symbol = "[îŸ… ](green)"

[directory]
truncation_length = 1
style = "bold pink"

[battery]
disabled = true
full_symbol = "ó±ˆ‘"
charging_symbol = "ó°‚„"
discharging_symbol = "ó°‚Œ"
# ignore_percentage= ['83']
unknown_symbol = "ó°‚‘"
format = "[$symbol]($style) $percentage"

[[battery.display]]
style = "italic mauve"
threshold=100

[git_branch]
symbol = 'ðŸŒ± '
truncation_length = 10
truncation_symbol = ''
ignore_branches = ['main']
format = "[ $symbol$branch]($style) "
style = " rosewater"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
